import { ApiSurface } from "./types.js";

/**
 * Exports an ApiSurface to a valid OpenAPI 3.0.0 JSON object.
 */
export function exportToOpenApi(surface: ApiSurface): any {
  const openapi: any = {
    openapi: "3.0.0",
    info: {
      title: "Reconstructed API Surface",
      version: "1.0.0",
      description: "Automatically generated by JS Cartographer"
    },
    paths: {}
  };

  if (surface.baseUrl) {
    openapi.servers = [{ url: surface.baseUrl }];
  }

  for (const endpoint of surface.endpoints) {
    const path = endpoint.path || "/";
    if (!openapi.paths[path]) {
      openapi.paths[path] = {};
    }

    const method = endpoint.method.toLowerCase();
    const op: any = {
      responses: {
        "200": {
          description: "Successful response"
        }
      }
    };

    if (endpoint.queryParams && endpoint.queryParams.length > 0) {
      op.parameters = endpoint.queryParams.map((p) => ({
        name: p.name,
        in: "query",
        required: p.required,
        schema: {
          type: p.type
        }
      }));
    }

    if (endpoint.requestBody) {
      op.requestBody = {
        content: {
          "application/json": {
            schema: {
              type: "object",
              properties: {}
            }
          }
        }
      };
      for (const [name, type] of Object.entries(endpoint.requestBody)) {
        op.requestBody.content["application/json"].schema.properties[name] = {
          type: type
        };
      }
    }

    openapi.paths[path][method] = op;
  }

  return openapi;
}
